project:
  type: website

website:
  title: "Template Workshop"
  favicon: img/favicon.ico
  repo-url: https://github.com/Lars-B/
  site-url: example.com
  navbar:
    logo: img/coffee_can.png
    title: false
    left:
      - text: "Home"
        href: index.qmd
        icon: house
      - text: "Session 1"
        href: pages/session1.qmd
        icon: activity
      - text: "Session 2"
        href: pages/session2.qmd
        icon: box-seam
      - text: "{{< fa brands r-project >}} embedding"
        href: pages/embedR.qmd
      - text: "PDF embedding"
        href: pages/embedPDF.qmd
        icon: file-earmark-pdf
      - text: "About"
        href: about.qmd
        icon: airplane-engines
    tools:
      - icon: github
        href: https://github.com/Lars-B/
        target: _blank
        aria-label: GitHub organization

format:
  html:
    theme: cosmo
    css: css/styles.css
